# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    configs:
        private_config:
            toolbar: full
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []
        public_config:
            toolbar: full